### ISSUE TITLE
Working with CI

### ISSUE THREAD

**Issue by Nigui** [tibdex/autorebase#15]
I'm currently using autorebase in one of my projects building with CircleCI.

The problem is that autorebase (through its dependencies) creates temporary branch in order to rebase. During the build, Circle tries to checkout this branch, and fails because it has been already removed.

My point is : can we imagine a workaround which lets us to choose the temporary branch name in order to be able to ignore it on CI tools ? 

Today, temporary branch name seems to be based on these two lines : 

- https://github.com/tibdex/github-cherry-pick/blob/master/src/index.js#L256
- https://github.com/tibdex/shared-github-internals/blob/master/src/git.js#L22

**Comment by tibdex** [comment]
Hi Guillaume, I use CircleCI too in most of my projects and I always enable the [option to only build pull requests](https://circleci.com/docs/2.0/oss/#only-build-pull-requests). Then CircleCI completely ignores the temporary branches created by Autorebase dependencies. Have you considered enabling this option too?

**Comment by zaccolley** [comment]
@Nigui @tibdex Hi both, we had this problem and just so you're aware you can also ignore branches in CircleCI for example:

```yaml
filters:
  branches:
    ignore:
      # ignore branches created by autorebase https://github.com/tibdex/autorebase
      - /rebase-pull-request-.*/
      - /cherry-pick-rebase-pull-request-.*/
```

https://circleci.com/docs/2.0/configuration-reference/#branches
